#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_org="0.0.1"
  jq -n --arg fogg_org "$ver_fogg_org" '{fogg_org: $fogg_org}'
}

version "$@"
